stages:
  - lint
  - build
  - deploy

eslint:
  image: node:latest
  stage: lint
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js .
  tags:
    - spot


build:
  image: node:latest
  stage: build
  script:
    - npm build
  tags:
    - spot

cache:
  paths:
    - node_modules/
