version: "2"

services:
  bifrost-postgres:
    image: postgres:11.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bifrost
      POSTGRES_DB: bifrost

  heimdall-mock:
    build: ../heimdall-mock/
    environment:
      - NODE_ENV=local
    ports:
      - "3001:3000"
    volumes:
      - ../heimdall-mock:/app/heimdall-mock
      - /app/heimdall-mock/node_modules

  bifrost:
    build: ./
    depends_on:
      - bifrost-postgres
      - heimdall-mock
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/bifrost
      - /app/bifrost/node_modules

  components-serve:
    build:
      context: ../bifrost-components/
      dockerfile: dockerfile.serve
    ports:
      - "3334:3333"
    volumes:
      - ../bifrost-components/:/app/serve/

  components-watch:
    build:
      context: ../bifrost-components/
      dockerfile: dockerfile.watch
    volumes:
      - ../bifrost-components/:/app/watch/

  demo-shop:
    build: ../demo-shop/
    ports:
      - "3002:3000"
    depends_on:
      - components-serve
      - components-watch
    volumes:
      - ../demo-shop:/app/demoshop
      - /app/demoshop/node_modules