orbs:
  heroku: circleci/heroku@0.0.8
  node: circleci/node@1.1
version: 2.1
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
jobs:
  build:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: 12.13.1
          npm-version: 6.13.6
          install-yarn: false
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test-all

  deploy:
    executor: heroku/default # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - checkout
      - heroku/install # Runs the heroku install command, if necessary.
      - heroku/deploy-via-git: # Deploys branch to Heroku via git push.
          only-branch: master # If you specify an only-branch, the deploy will not occur for any other branch.
