orbs:
  heroku: circleci/heroku@0.0.8
  node: circleci/node@1.1
version: 2.1
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
      - deploy-staging:
          requires:
            - deploy-dev
jobs:
  build:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: 12.13.1
          npm-version: 6.13.6
          install-yarn: false
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test-all

  deploy-dev:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
          app-name: wertgarantie-bifrost-dev
  deploy-staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
          app-name: wertgarantie-bifrost-staging
